import "~/app/main.css"

import type { Metadata } from 'next'
import { Lato } from "next/font/google"
import { ReactNode } from "react"

const lato = Lato({ subsets: ["latin"], weight: "700" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" className={lato.className}>
      <body >{children}</body>
    </html>
  )
}
